---
target:
  skipper:
    use: 
      - azure.common
    components:
      - output_path: .
        input_paths:
          - AzureReadme.md
          - inventory.json
        rename:
          - input_path: AzureReadme.md
            filename: README.md
    secrets:
      drivers:
        azurekv: 
          vault_name: "%{env:AZURE_KEY_VAULT_NAME}"
          # ignore_version: true
      keys:
        azurekv: "test1"
        # azurekv: "https://skipperkeyvaultexample.vault.azure.net/keys/test1/87ab487b65c44f4cb4feec758538a227"

  secrets:
    test1: ?{azurekv:targets/${target_name}/test1||randomstring:32}
    test2: ?{azurekv:targets/${target_name}/test2||randomstring:64}


