---
target:
  use: 
    - azure.resources
    - terraform.identifiers

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
